In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(10,4))
print X

[[ -1.34401097   7.79007328  -6.64280945   4.05618601]
 [ -4.32831864  -1.30019098   8.00933678   9.74992515]
 [  6.22373286   6.21156308   8.10746267   7.7187554 ]
 [  0.47715028   0.64564725  -0.63478761   9.07729173]
 [  8.99362643  -7.18909099 -13.80299446  -1.94688258]
 [ 16.83584467  20.33450917   1.71638748   3.79442396]
 [ -5.47618883  -5.90769936  -6.40214554  20.20159069]
 [ 12.39191583  17.79714451   6.95288137   0.67841526]
 [-12.05634731   3.70081406 -15.69705942  24.8214617 ]
 [ 15.35721193 -15.31199922   8.29180828 -10.62192716]]


In [3]:
X_norm = ((X - np.mean(X,axis=0)) / np.std(X,axis=0))

In [4]:
index = [i for i in range(X.shape[0]) if np.sum(X,axis=1)[i] > 10]

In [5]:
index

[1, 2, 5, 7]

In [6]:
print np.nonzero(np.sum(X,axis=1) > 10)

(array([1, 2, 5, 7]),)


In [7]:
A = np.eye(3)
B = np.eye(3)

In [8]:
AB = np.vstack((A, B))
print AB

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
np.hstack((A,B))

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])